# Generated by Django 3.1 on 2020-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_pub',
            field=models.BooleanField(default=True),
        ),
    ]
